name: Build and Publish Web Site

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate RSS
      run: node generate-rss.js

    - name: Redirect 404 to Index for SPA
      run: cp index.html 404.html

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update RSS feed'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        cname: digikaladiscounts.com
